# Generated by Django 3.0.5 on 2020-05-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0004_auto_20200525_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_info',
            field=models.TextField(max_length=8000, verbose_name='Текст'),
        ),
    ]
