# Generated by Django 3.0.5 on 2020-05-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_auto_20200507_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('question_multi', models.BooleanField(choices=[('Мулти', True), ('Одиночный', False)], default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='TestApp.Album')),
            ],
            options={
                'unique_together': {('album',)},
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='TestApp.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question',)},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='track',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
