# Generated by Django 3.0.5 on 2020-05-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0005_auto_20200507_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_multi',
            field=models.BooleanField(choices=[('Мулти', True), ('Одиночный', False)], default=False, verbose_name='Мульти'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='TestApp.Test'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test',)},
        ),
        migrations.RemoveField(
            model_name='question',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
