# Generated by Django 3.0.5 on 2020-05-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0008_auto_20200507_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
