# Generated by Django 3.0.5 on 2020-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0012_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='сorrect_answer',
            field=models.BooleanField(choices=[(False, 'Нет'), (True, 'Да')], default=False),
        ),
    ]
