# Generated by Django 3.0.5 on 2020-05-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0014_auto_20200507_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_answer',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
