# Generated by Django 3.0.5 on 2020-05-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0017_userstat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userstat',
            new_name='Results',
        ),
    ]
